/**
 * External Agent Types
 *
 * Defines the HTTP contract between platform and external agents.
 *
 * @see /docs/designs/external-agents/TECH_DESIGN.md
 */

import type { AgentUsage, ModelUsage } from '@/types';

// Re-export shared types for convenience
export type { AgentUsage, ModelUsage };

// =============================================================================
// REQUEST TYPES
// =============================================================================

/**
 * Request sent to agent's POST /execute endpoint
 */
export interface AgentExecuteRequest {
  /** Unique reference for this request (for idempotency) */
  request_id: string;

  /** The prompt to execute (generated by Prompt Agent) */
  prompt: string;

  /** Requirements context (helps agent understand expectations) */
  requirements?: string[];

  /** Callback URL for async completion notification */
  callback_url?: string;

  /** Retry context when this is a retry attempt */
  adjustment?: AgentAdjustmentContext;
}

/**
 * Context provided when retrying a failed execution
 */
export interface AgentAdjustmentContext {
  is_retry: boolean;
  attempt: number;
  previous_output: unknown;
  issues: Array<{
    criterion: string;
    detail: string;
  }>;
  feedback: string;
}

// =============================================================================
// RESPONSE TYPES - Execute
// =============================================================================

/**
 * Synchronous response - task completed immediately
 */
export interface AgentExecuteResponseSync {
  status: 'completed';
  output: unknown;
  usage: AgentUsage;
  processing_time_ms?: number;
}

/**
 * Asynchronous response - task accepted for processing
 */
export interface AgentExecuteResponseAsync {
  status: 'accepted';
  reference_id: string;
  status_url: string;
  estimated_completion_ms?: number;
  supports_callback: boolean;
}

/** Union type for execute response */
export type AgentExecuteResponse = AgentExecuteResponseSync | AgentExecuteResponseAsync;

// =============================================================================
// RESPONSE TYPES - Status Polling
// =============================================================================

/**
 * Status response - task still processing
 */
export interface AgentStatusResponseProgress {
  status: 'processing';
  progress?: number;           // 0-1
  message?: string;            // "Generating image..."
  estimated_remaining_ms?: number;
}

/**
 * Status response - task completed successfully
 */
export interface AgentStatusResponseCompleted {
  status: 'completed';
  output: unknown;
  usage: AgentUsage;
  processing_time_ms?: number;
}

/**
 * Status response - task failed
 */
export interface AgentStatusResponseFailed {
  status: 'failed';
  error: string;
  retryable: boolean;
}

/** Union type for status response */
export type AgentStatusResponse =
  | AgentStatusResponseProgress
  | AgentStatusResponseCompleted
  | AgentStatusResponseFailed;

// =============================================================================
// CALLBACK TYPES
// =============================================================================

/**
 * Callback request sent from agent to platform when async task completes
 */
export interface AgentCallbackRequest {
  reference_id: string;
  status: 'completed' | 'failed';
  output?: unknown;            // If completed
  error?: string;              // If failed
  usage: AgentUsage;           // REQUIRED even on failure (partial cost tracking)
  processing_time_ms?: number;
}

// =============================================================================
// REGISTRATION TYPES
// =============================================================================

/**
 * Agent registration schema for marketplace
 */
export interface AgentRegistration {
  // Identity
  name: string;
  description: string;
  url: string;

  // Pricing
  pricing: {
    base_price: number;        // Price per execution in USDC
    negotiable: boolean;
    min_price?: number;        // Minimum if negotiable
  };

  // Capabilities (for discovery)
  capabilities: string;        // Natural language description
  tags?: string[];

  // Technical
  supports_async: boolean;
  supports_callback: boolean;
  max_concurrent?: number;     // Rate limit

  // Payment
  wallet: string;              // Agent's payment address

  // Contact
  owner_email?: string;
}

// =============================================================================
// TYPE GUARDS
// =============================================================================

/** Check if execute response is synchronous (completed) */
export function isExecuteResponseSync(
  response: AgentExecuteResponse
): response is AgentExecuteResponseSync {
  return response.status === 'completed';
}

/** Check if execute response is asynchronous (accepted) */
export function isExecuteResponseAsync(
  response: AgentExecuteResponse
): response is AgentExecuteResponseAsync {
  return response.status === 'accepted';
}

/** Check if status response indicates completion */
export function isStatusCompleted(
  response: AgentStatusResponse
): response is AgentStatusResponseCompleted {
  return response.status === 'completed';
}

/** Check if status response indicates failure */
export function isStatusFailed(
  response: AgentStatusResponse
): response is AgentStatusResponseFailed {
  return response.status === 'failed';
}

/** Check if status response indicates still processing */
export function isStatusProcessing(
  response: AgentStatusResponse
): response is AgentStatusResponseProgress {
  return response.status === 'processing';
}
