/**
 * Mock Agent API - Execute Endpoint
 *
 * Simulates an external agent for testing the end-to-end flow.
 * Supports both sync and async modes with configurable behavior.
 *
 * Query Parameters:
 *   - mode: 'sync' | 'async' (default: 'sync')
 *   - delay: number (ms to wait before responding, default: 100)
 *   - fail: boolean (simulate failure, default: false)
 *   - fail_rate: number (0-1, random failure probability, default: 0)
 *
 * @example
 *   POST /api/mock-agent/execute?mode=sync&delay=500
 *   POST /api/mock-agent/execute?mode=async
 *   POST /api/mock-agent/execute?fail=true
 */

import { NextRequest, NextResponse } from 'next/server';
import { randomUUID } from 'crypto';
import type {
  AgentExecuteRequest,
  AgentExecuteResponseSync,
  AgentExecuteResponseAsync,
  AgentUsage,
} from '@/lib/external-agents/types';
import { asyncJobs } from '../store';

export async function POST(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;

  // Parse configuration from query params
  const mode = (searchParams.get('mode') || 'sync') as 'sync' | 'async';
  const delay = parseInt(searchParams.get('delay') || '100', 10);
  const shouldFail = searchParams.get('fail') === 'true';
  const failRate = parseFloat(searchParams.get('fail_rate') || '0');

  // Parse request body
  let body: AgentExecuteRequest;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: 'Invalid JSON body' },
      { status: 400 }
    );
  }

  // Validate required fields
  if (!body.request_id || !body.prompt) {
    return NextResponse.json(
      { error: 'Missing required fields: request_id, prompt' },
      { status: 400 }
    );
  }

  // Check for random failure
  const randomFail = failRate > 0 && Math.random() < failRate;
  if (shouldFail || randomFail) {
    return NextResponse.json(
      {
        status: 'failed',
        error: 'Mock agent simulated failure',
        retryable: true,
      },
      { status: 500 }
    );
  }

  // Handle sync mode
  if (mode === 'sync') {
    // Simulate processing delay
    if (delay > 0) {
      await new Promise((resolve) => setTimeout(resolve, delay));
    }

    const response: AgentExecuteResponseSync = {
      status: 'completed',
      output: generateMockOutput(body),
      usage: generateMockUsage(body),
      processing_time_ms: delay,
    };

    return NextResponse.json(response);
  }

  // Handle async mode
  const referenceId = randomUUID();
  const baseUrl = new URL(request.url).origin;
  const completionDelay = parseInt(searchParams.get('async_delay') || '3000', 10);

  // Store job for status polling
  asyncJobs.set(referenceId, {
    request: body,
    startTime: Date.now(),
    completionTime: Date.now() + completionDelay,
    callbackUrl: body.callback_url,
  });

  // Schedule callback if provided
  if (body.callback_url) {
    scheduleCallback(referenceId, body, completionDelay);
  }

  const response: AgentExecuteResponseAsync = {
    status: 'accepted',
    reference_id: referenceId,
    status_url: `${baseUrl}/api/mock-agent/status/${referenceId}`,
    estimated_completion_ms: completionDelay,
    supports_callback: true,
  };

  return NextResponse.json(response, { status: 202 });
}

/**
 * Generate mock output based on the input prompt.
 *
 * Output structure matches what dispatch.ts expects:
 * - For sync/status responses: raw output (dispatch extracts title/description)
 * - For callbacks: { title, description, content } structure
 */
function generateMockOutput(request: AgentExecuteRequest, forCallback = false): unknown {
  const isRetry = request.adjustment?.is_retry ?? false;
  const attempt = request.adjustment?.attempt ?? 1;

  const content = {
    prompt_received: request.prompt.substring(0, 100) + (request.prompt.length > 100 ? '...' : ''),
    requirements_count: request.requirements?.length ?? 0,
    is_retry: isRetry,
    attempt_number: attempt,
    generated_at: new Date().toISOString(),
    mock_data: {
      headline: 'Sample Headline Generated by Mock Agent',
      body: 'This is sample body content that would normally be generated by the actual agent.',
      cta: 'Click Here',
      confidence: 0.95,
    },
  };

  // For callbacks, wrap in { title, description, content } as expected by dispatch
  if (forCallback) {
    return {
      title: 'Mock Agent Response',
      description: `Generated response for request ${request.request_id}`,
      content,
    };
  }

  // For sync/status responses, include title/description at root for helper extraction
  return {
    title: 'Mock Agent Response',
    description: `Generated response for request ${request.request_id}`,
    ...content,
  };
}

/**
 * Generate mock usage data for billing
 */
function generateMockUsage(request: AgentExecuteRequest): AgentUsage {
  // Simulate cost based on prompt length
  const promptTokens = Math.ceil(request.prompt.length / 4);
  const completionTokens = 500; // Fixed mock completion
  const costPer1k = 0.015; // Mock cost per 1k tokens

  const totalCost = ((promptTokens + completionTokens) / 1000) * costPer1k;

  return {
    total_cost: Math.round(totalCost * 10000) / 10000, // Round to 4 decimals
    model_usage: [
      {
        model: 'mock-agent/default-v1',
        native_tokens_prompt: promptTokens,
        native_tokens_completion: completionTokens,
        total_cost: totalCost,
      },
    ],
  };
}

/**
 * Schedule a callback for async completion
 */
function scheduleCallback(
  referenceId: string,
  request: AgentExecuteRequest,
  delayMs: number
) {
  setTimeout(async () => {
    const job = asyncJobs.get(referenceId);
    if (!job?.callbackUrl) return;

    try {
      // Callback uses { title, description, content } structure
      const callbackPayload = {
        reference_id: referenceId,
        status: 'completed',
        output: generateMockOutput(request, true), // forCallback=true
        usage: generateMockUsage(request),
        processing_time_ms: delayMs,
      };

      await fetch(job.callbackUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(callbackPayload),
      });

      console.log(`[MockAgent] Callback sent to ${job.callbackUrl}`);
    } catch (error) {
      console.error(`[MockAgent] Callback failed:`, error);
    }
  }, delayMs);
}
