/**
 * AgentsStack External Agent HTTP Contract Types
 *
 * These types match the AgentsStack platform's external agent contract.
 * Reference: /lib/external-agents/types.ts
 */

// =============================================================================
// Request Types
// =============================================================================

/**
 * Adjustment context for retry requests
 */
export interface AgentAdjustmentContext {
  is_retry: boolean;
  attempt: number;
  previous_output: unknown;
  issues: Array<{
    criterion: string;
    detail: string;
  }>;
  feedback: string;
}

/**
 * Execute request from AgentsStack platform
 */
export interface AgentExecuteRequest {
  /** Unique identifier for this request (idempotency) */
  request_id: string;

  /** The prompt to execute (generated by Prompt Agent) */
  prompt: string;

  /** Optional requirements context */
  requirements?: string[];

  /** Optional callback URL for async completion notifications */
  callback_url?: string;

  /** Optional retry context from previous attempt */
  adjustment?: AgentAdjustmentContext;
}

// =============================================================================
// Response Types
// =============================================================================

/**
 * Async response - task accepted and will be processed
 */
export interface AgentExecuteResponseAsync {
  status: 'accepted';

  /** Reference ID for polling status */
  reference_id: string;

  /** Status polling URL */
  status_url: string;

  /** Estimated completion time in milliseconds */
  estimated_completion_ms?: number;

  /** Whether agent supports callback notifications */
  supports_callback: boolean;
}

/**
 * Sync response - task completed immediately
 */
export interface AgentExecuteResponseSync {
  status: 'completed';

  /** Task output */
  output: unknown;

  /** Usage and cost information */
  usage: AgentUsage;

  /** Processing time in milliseconds */
  processing_time_ms?: number;
}

/**
 * Union of possible execute responses
 */
export type AgentExecuteResponse =
  | AgentExecuteResponseAsync
  | AgentExecuteResponseSync;

// =============================================================================
// Status Types
// =============================================================================

/**
 * Status response - task is still processing
 */
export interface AgentStatusResponseProcessing {
  status: 'processing';

  /** Progress from 0 to 1 */
  progress?: number;

  /** Optional status message */
  message?: string;
}

/**
 * Status response - task completed successfully
 */
export interface AgentStatusResponseCompleted {
  status: 'completed';

  /** Task output */
  output: ImageGenerationOutput;

  /** Usage and cost information */
  usage: AgentUsage;

  /** Processing time in milliseconds */
  processing_time_ms?: number;
}

/**
 * Status response - task failed
 */
export interface AgentStatusResponseFailed {
  status: 'failed';

  /** Error message */
  error: string;

  /** Whether the task is retryable */
  retryable: boolean;
}

/**
 * Union of possible status responses
 */
export type AgentStatusResponse =
  | AgentStatusResponseProcessing
  | AgentStatusResponseCompleted
  | AgentStatusResponseFailed;

// =============================================================================
// Callback Types
// =============================================================================

/**
 * Callback request sent to platform when task completes
 */
export interface AgentCallbackRequest {
  /** Reference ID from original execute response */
  reference_id: string;

  /** Task completion status */
  status: 'completed' | 'failed';

  /** Task output (if completed) */
  output?: unknown;

  /** Error message (if failed) */
  error?: string;

  /** Usage and cost information */
  usage: AgentUsage;

  /** Processing time in milliseconds */
  processing_time_ms?: number;
}

// =============================================================================
// Usage & Cost Tracking
// =============================================================================

/**
 * Model usage details (per-model breakdown)
 */
export interface ModelUsage {
  /** Model identifier (e.g., "google/gemini-2.0-flash-exp:image") */
  model: string;

  /** Input tokens (optional) */
  native_tokens_prompt?: number;

  /** Output tokens (optional) */
  native_tokens_completion?: number;

  /** Cost for this model call in USD */
  total_cost: number;
}

/**
 * Agent usage information
 * Price is MANDATORY, token breakdown is OPTIONAL
 */
export interface AgentUsage {
  /** Total cost in USD (REQUIRED) */
  total_cost: number;

  /** Optional per-model breakdown (for multi-model flows) */
  model_usage?: ModelUsage[];
}

// =============================================================================
// Output Types (Agent-Specific)
// =============================================================================

/**
 * Image generation output format
 */
export interface ImageGenerationOutput {
  image: {
    /** URL to generated image */
    url: string;

    /** Image width in pixels */
    width: number;

    /** Image height in pixels */
    height: number;

    /** Image format (png, jpg, webp, etc.) */
    format: string;
  };

  /** Alt text for accessibility */
  alt_text: string;

  /** The actual prompt used for generation */
  prompt_used?: string;

  /** Model used for generation */
  model_used?: string;
}
